### ISSUE TITLE
[BUG] Windows in audacity are black and thus unusable

### ISSUE THREAD

**Issue by GithubUser699** [vinceliuice/Colloid-gtk-theme#103]
### Issue
Windows in audacity are black. Everything inside it is not visible.
### Steps to reproduce
1. Apply Colloid-Light
2. Open audacity
3. Press r to start a recording, after at least a second press space to end recording
4. Press Control+a to select the track
5. go to effect → compressor (or any other option there)

Here is what I see (I started audacity with `GTK_DEBUG=interactive audacity`):

_Fig. 1: That's what it looks like with your theme but no changes._
![aud_orig](https://user-images.githubusercontent.com/74927253/223034882-d5f71e51-b7ce-4a6b-865c-69adcb5919dd.png)

_Fig. 2: That's what it looks like if I turn on "Dark Variant" from GTK debug window._
![aud_darkVariant](https://user-images.githubusercontent.com/74927253/223035166-9e397f3a-b698-44cc-9fdc-f1bf1a72b151.png)

_Fig. 3:_ That's what it looks like with your default theme (without "Dark Variant"), but adding `* { background-color: #ffffff}` ([Inspired by this post](https://stackoverflow.com/questions/12249257/background-of-custom-gtk-widget-is-rendered-solid-black)).
![aud_wildglob](https://user-images.githubusercontent.com/74927253/223035433-c016ed96-577f-46fa-aa3e-e2103bf77c11.png)

While setting the background color somewhat works, it also breaks a lot of other parts and apps if you where to insert that line into gtk-3.0/gtk.css.

I don't know a thing about theming, but maybe the background is set to dark somewhere where it shouldn't be? If you know a fix, please let me know!

### System info

OS: Debian GNU/Linux
OS version: 11 (bullseye)
GNOME version: 3.38.5
window manager: X11

**Comment by vinceliuice** [comment]
![Screenshot_20230916_220332](https://github.com/vinceliuice/Colloid-gtk-theme/assets/7604295/9242f6f8-47bd-43a7-bc6b-e975d89bba60)

**Comment by vinceliuice** [comment]
I'm using gnome 44.4
