### ISSUE TITLE
Firefox 111.0.1 theme broken

### ISSUE THREAD

**Issue by Teddy-Kun** [vinceliuice/Colloid-gtk-theme#104]
Since the latest Firefox update the selection of Dark/Light theme is broken. Here are some pics:

Dark Theme:
![20230324_08h29m32s_grim](https://user-images.githubusercontent.com/58993831/227454361-e53be983-4059-4fc9-806c-de0f865b0086.png)

Light Theme:
![20230324_08h29m50s_grim](https://user-images.githubusercontent.com/58993831/227454397-9169052d-e588-494e-93a4-fb0748c71575.png)

**Comment by vinceliuice** [comment]
Not a theme issue, this is a firefox issue, you can use the dark mode in firefox setting

**Comment by Teddy-Kun** [comment]
Aight thank you I have no idea why that suddenly happend after the update but you are right.
