### ISSUE TITLE
gnome file manager and web store isn't using the colloid theme (fully)

### ISSUE THREAD

**Issue by mohammad-zadeed** [vinceliuice/Colloid-gtk-theme#112]
left side is brave and right side is gnome file manager
brave uses this red green yellow colour scheme but the file manager isn't , how to fix that?
![Screenshot from 2023-04-27 05-46-10](https://user-images.githubusercontent.com/120179019/234725936-fdd5d399-ff9c-490d-be3f-f8fe61cc3120.png)

**Comment by vinceliuice** [comment]
Just run: `./install.sh -l -c dark`

**Comment by mohammad-zadeed** [comment]
But i didn't download it from here , i downloaded the file from pling and extracted it in .themes folder
How to fix it

**Comment by vinceliuice** [comment]
You can only download from here and run this to fix it
