### ISSUE TITLE
Almost all Vince's themes broken on Gnome 44.1

### ISSUE THREAD

**Issue by JurijOrlow** [vinceliuice/Colloid-gtk-theme#113]
Colloid, Orchis, Qogir, Vimix, all of them have MASSIVE graphical artifacts on Gnome 44.1 (Fedora 38). They appear as huge bars outside the window (black in Wayland, "cut out of wallpaper" in X11). Almost all non-Gnome apps - Discord, Slack, Caprine, Virtualbox, Asbru CM, Teamviewer have this issue. Maximizing and un-maximizing helps, but when you launch app again, it shows again. For now the worst is Orchis, the least annoying is Vimix (it only has 2 small black squares below window). 
Tested on 2 laptops with Intel 11th gen CPUs with Intel Iris Xe and on Ryzen 7700X CPU PC with Radeon 7900XTX. Attaching screenshots.
![obraz](https://user-images.githubusercontent.com/32055243/235522832-0ff696d2-665a-4806-946b-0f1165639663.png)
![obraz](https://user-images.githubusercontent.com/32055243/235522858-118bda60-4584-4f5d-a50e-947bb3443de7.png)
![obraz](https://user-images.githubusercontent.com/32055243/235522868-b3f03d30-0482-42a8-9622-f6e4d85a40ac.png)

**Comment by vinceliuice** [comment]
https://gitlab.gnome.org/GNOME/mutter/-/issues/2725

**Comment by vinceliuice** [comment]
Since 44 the titlebar is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting XWAYLAND_NO_GLAMOR=1 in ~/.config/environment.d/00-no-glamor.conf and then restarting your session.

**Comment by Raiden0456** [comment]
> Since 44 the titlebar is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting `XWAYLAND_NO_GLAMOR=1` in `~/.config/environment.d/00-no-glamor.conf` and then restarting your session.

Can't seem to find the file you've specified. :(

**Comment by Raiden0456** [comment]
> Since 44 the titlebar is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting `XWAYLAND_NO_GLAMOR=1` in `~/.config/environment.d/00-no-glamor.conf` and then restarting your session.

Thanks, that helped, although I guess that's a temporary fix?

**Comment by vinceliuice** [comment]
This is a Gnome windows manager app: mutter issue, so we need to wait Gnome team fix this

**Comment by peppidesu** [comment]
> Since 44 the titlebar is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting `XWAYLAND_NO_GLAMOR=1` in `~/.config/environment.d/00-no-glamor.conf` and then restarting your session.

My laptop is running x11, is there an equivalent temporary fix for that? (Arch Linux with proprietary nvidia drivers)

**Comment by D3vil0p3r** [comment]
> XWAYLAND_NO_GLAMOR=1

This fix does not work for me sadly:
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/83867734/8bec33fd-94bf-48f1-a67d-2a05ee6406b6)

**Comment by yukiqt** [comment]
> > XWAYLAND_NO_GLAMOR=1
> 
> This fix does not work for me sadly (PS: I'm on Xorg):

Same issue here, also on Xorg (nvidia-open drivers).
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/83128586/98653026-a5c8-44b6-aca6-08e0166bf5a7)
```
$ pacman -Q | grep nvidia-open-dkms
nvidia-open-dkms 530.41.03-10
```

**Comment by peppidesu** [comment]
I got the theme to work again by cleverly mixing changes from https://github.com/vinceliuice/Graphite-gtk-theme/commit/925619e92f892e72f8fcf25fa8ad08fa1330e1b9 into this project. Vince's prior approach to `shadow-box` seems to be the culprit, although I have not done my research.

I am not turning this into a pull request since I made some radical changes to some of the code and removed a lot as well, and I have little experience using css (beyond the simple stuff that is). But if someone wants to give fixing it a try I am happy to share my changes that made it work on my machine.

**Comment by Aspromayros** [comment]
> I got the theme to work again by cleverly mixing changes from [vinceliuice/Graphite-gtk-theme@925619e](https://github.com/vinceliuice/Graphite-gtk-theme/commit/925619e92f892e72f8fcf25fa8ad08fa1330e1b9) into this project. Vince's prior approach to using `shadow-box` seems to be the culprit, although I have not done my research on why that happens.
> 
> I am not turning this into a pull request since I made some radical changes to some of the code and removed a lot as well, and I have little experience using css (beyond the simple stuff that is). But if someone wants to give fixing it a try I am happy to share my changes that made it work on my machine.

Yes, i would like to fix it since the gruvbox variant with legacy buttons looks awesome.

**Comment by peppidesu** [comment]
> > I got the theme to work again by cleverly mixing changes from [vinceliuice/Graphite-gtk-theme@925619e](https://github.com/vinceliuice/Graphite-gtk-theme/commit/925619e92f892e72f8fcf25fa8ad08fa1330e1b9) into this project. Vince's prior approach to using `shadow-box` seems to be the culprit, although I have not done my research on why that happens.
> > I am not turning this into a pull request since I made some radical changes to some of the code and removed a lot as well, and I have little experience using css (beyond the simple stuff that is). But if someone wants to give fixing it a try I am happy to share my changes that made it work on my machine.
> 
> Yes, i would like to fix it since the gruvbox variant with legacy buttons looks awesome.

I put the changes into a commit on my fork of the theme. This commit doesn't contain the artistic changes i made in that fork, just the fix (except for the interpolate-color script, you can ignore that).

https://github.com/peppidesu/Colloid-gtk-theme-ayu/commit/22416d48d187251688dc45f004043d6b1e804c60

**Comment by NelloKudo** [comment]
> Since 44 the titlebar is rendered using gtk4 with the cairo backend and cairo uses XRender on X11 surfaces - which is what glamor tries to accelerate. I would suggest to try disabling glamor by putting `XWAYLAND_NO_GLAMOR=1` in `~/.config/environment.d/00-no-glamor.conf` and then restarting your session.

For those wondering, this fix breaks a lot of games under XWayland, so make sure you're actually disabling that while gaming.
