### ISSUE TITLE
Nautilus, Console, and other apps have White Backgrounds - Fedora 38

### ISSUE THREAD

**Issue by SharpStormGames** [vinceliuice/Colloid-gtk-theme#114]
On some apps like Nautilus, Console, Text Editor, all have white background when the Colloid-Dark theme is selected for both Shell and Legacy Apps. Most Flatpak apps are not using Colloid as the theme. I am running Fedora 38.

**Comment by vinceliuice** [comment]
Run: `./install.sh -c dark -l`

**Comment by SharpStormGames** [comment]
ty
