### ISSUE TITLE
[Feature request] Add floating top panel tweak, like in Graphite

### ISSUE THREAD

**Issue by JurijOrlow** [vinceliuice/Colloid-gtk-theme#116]
During the time, when Colloid was broken on Gnome 44 I tried Graphite, and I fell in love with this floating top panel tweak. It looks so slick and modern.
Is it possible to add such tweak to Colloid, as it's my default theme of choice? This would be great.
Cheers

**Comment by vinceliuice** [comment]
Add support now, Run `./install.sh --tweaks float` to install it
