### ISSUE TITLE
Dash to panel view problem

### ISSUE THREAD

**Issue by ceyhunn** [vinceliuice/Colloid-gtk-theme#117]
Hi @vinceliuice ,

I use dash-to-panel extension and recently I also updated Colloid-gtk-theme.
When panel on left or right side position, status bar , extension tray icons become tiny.
![Screenshot from 2023-06-21 13-32-35](https://github.com/vinceliuice/Colloid-gtk-theme/assets/5506156/81b6b433-9c9a-4b98-950a-9ef7d3ade7d3)

with adwaita it is ok,
![Screenshot from 2023-06-21 13-33-24](https://github.com/vinceliuice/Colloid-gtk-theme/assets/5506156/1cab9f2b-d9ec-4275-838f-e722a14b0b89)

**Comment by ceyhunn** [comment]
Thank you for quick fix, but some tray icons are not showed:
![Screenshot from 2023-06-21 18-00-05](https://github.com/vinceliuice/Colloid-gtk-theme/assets/5506156/9c354654-d0ca-4161-a200-4d2c16c5c4d5)

**Comment by vinceliuice** [comment]
Restart your desktop

**Comment by ceyhunn** [comment]
After restart, issue still exists.
