### ISSUE TITLE
Memory leak occurred on xfce4 global appmenu

### ISSUE THREAD

**Issue by ging-dev** [vinceliuice/Colloid-gtk-theme#12]
Same problem as: https://github.com/vinceliuice/vimix-gtk-themes/issues/188
![image](https://user-images.githubusercontent.com/42226341/147377462-54437908-ad0d-4a76-b1e5-f852307c6cb4.png)

**Comment by vinceliuice** [comment]
What's your desktop ann system version?

**Comment by vinceliuice** [comment]
I installed this one: https://aur.archlinux.org/packages/vala-panel-appmenu-xfce-git, but did not find this issue

**Comment by ging-dev** [comment]
> What's your desktop and system version?

Ubuntu 20.04 - xfce 4.16 with `xfce4-appmenu-plugin`

**Comment by vinceliuice** [comment]
I updated it, you can try if it fixed

**Comment by ging-dev** [comment]
> I updated it, you can try if it fixed

Looks like the bug has been fixed, thank you very much!

**Comment by vinceliuice** [comment]
You are welcome!
