### ISSUE TITLE
The rimless tweak doesn't remove 2px border around Nautilus

### ISSUE THREAD

**Issue by SolsticeSpectrum** [vinceliuice/Colloid-gtk-theme#139]
Nautilus has 2px border around it for some reason even tho no other app has it, even after using `rimless` tweak
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/38611351/20894d24-db26-41d2-8fc7-bd93856469c7)

I used Graphite theme before and it's `install.sh` script had `--tweaks rimless` option which removed this border in Nautilus so maybe study how that works here? https://github.com/vinceliuice/Graphite-gtk-theme

I also want to mention that there is this odd padding in Nautiluss
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/38611351/3e3f09b8-baae-4a1a-a420-1c390deca1a3)
I hope you can see the extra line that's there

**Comment by vinceliuice** [comment]
Run `./install.sh -l -r`

**Comment by SolsticeSpectrum** [comment]
Using --tweaks rimless works now perfectly and there are no longer any weird lines
