### ISSUE TITLE
Gnome 46 Support

### ISSUE THREAD

**Issue by EmptyVisual** [vinceliuice/Colloid-gtk-theme#149]
Hi Vince,

Currently there a few issues with the shell theme for 46 if these could be fixed please. It seems the shell widgets are out of place.

I'm using Black variant with Compact sizing

Calendar
![Screenshot from 2024-04-09 12-02-02](https://github.com/vinceliuice/Colloid-gtk-theme/assets/4710051/003e2f0b-5c58-4a6b-ad32-483f5939ff1f)

Media Player widget (using Quick Settings extension, not broken on default shell theme, only on Colloid GTK)
![Screenshot from 2024-04-09 12-03-11](https://github.com/vinceliuice/Colloid-gtk-theme/assets/4710051/02aba91f-932e-43f1-9b87-4ab11877dab2)

**Comment by EmptyVisual** [comment]
Thank you, Vince!
Looks like your commits have fixed the issues I was having with 46. 🎉

**Comment by vinceliuice** [comment]
You are welcome !
