### ISSUE TITLE
Suggestion to add a little margin between menu items

### ISSUE THREAD

**Issue by bakai-taalaibek** [vinceliuice/Colloid-gtk-theme#154]
Right now when I hover a menu item adjacent to selected menu item, there is no gap between them:
![Screenshot from 2024-04-28 10-57-09](https://github.com/vinceliuice/Colloid-gtk-theme/assets/121804957/b729209b-2ff2-4a6c-b7f2-87f240cf9406)

Here is an example from another theme:
![Screenshot from 2024-04-28 11-08-23](https://github.com/vinceliuice/Colloid-gtk-theme/assets/121804957/1e9668e9-ca63-46cf-b4a8-af8110477d15)

**Comment by vinceliuice** [comment]
Download the last update here and try again

**Comment by bakai-taalaibek** [comment]
Nothing changed. I cloned the repo again, run './install.sh -l -tweaks normal rimless', switched to another theme, then again to Colloid-Light. And the menu items still touch each other.

**Comment by vinceliuice** [comment]
![Screenshot from 2024-04-28 23-33-05](https://github.com/vinceliuice/Colloid-gtk-theme/assets/7604295/7ff52363-60b8-4efd-99cf-7b39cbb3ff1c)
this is on my desktop

**Comment by vinceliuice** [comment]
Tell me your desktop version ?

**Comment by vinceliuice** [comment]
What about now ?

**Comment by bakai-taalaibek** [comment]
Debian 12, Gnome 43.9. Reinstalled everything again. Nothing changed so far.

**Comment by vinceliuice** [comment]
What about now ?

**Comment by bakai-taalaibek** [comment]
I receive an error while trying to git clone
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/121804957/d572424d-f6d2-4452-be71-0dde56f3f64a)

So I download the zip file. But after having done all those steps, nothing changed yet.

**Comment by vinceliuice** [comment]
![Screenshot from 2024-04-29 16-12-09](https://github.com/vinceliuice/Colloid-gtk-theme/assets/7604295/19a662df-c954-44b0-8c22-852bb6df31d9)

**Comment by vinceliuice** [comment]
I tested on debian 12, it's already fixed
