### ISSUE TITLE
The installation script doesn't seem to be working

### ISSUE THREAD

**Issue by bakai-taalaibek** [vinceliuice/Colloid-gtk-theme#162]
I cloned the repo and run the "./install.sh -l --tweaks normal rimless" script. Here is the output
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/121804957/d56d1eaa-da74-4886-a925-b268d74baa68)

But it didn't put any folders in one the theme folders (home/.themes, usr/share/themes). And these are not available for selection in gnome tweaks. Downloading and moving theme folders manually works, but I wanted normal buttons and no borders.

**Comment by bakai-taalaibek** [comment]
I found the reason. I didn't realize that if I install the libadwaita theme, then the main gtk theme is not installed. The are on the opposite sides of an if-else statement:
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/121804957/08477fe4-9abe-4528-a2b6-869abe1a0cfc)

This also explains why your fix to my previous issue wasn't applying

**Comment by vinceliuice** [comment]
I rebuild libadwaita theme based on gnome default libadwaita theme. now it support switch system theme dark/light mode. so I make this option separate

**Comment by bakai-taalaibek** [comment]
What should I do to make it work? I run the script "./install.sh -l --tweaks normal rimless". But gnome apps' theme doesn't follow system theme. Are there extra steps I should do?

**Comment by bakai-taalaibek** [comment]
If I run "./install.sh -l --tweaks normal rimless", it doesn't apply adwaita theme. 
If I run "./install.sh -l", it applies adwaita theme, but I would like to have normal window buttons and no borders.

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Colloid-gtk-theme/assets/7604295/de6120fe-a5de-409e-a3f3-0ffd7fc3433d

**Comment by vinceliuice** [comment]
I tested on my desktop, it works well

**Comment by bakai-taalaibek** [comment]
Did the theme even change? In your video "before" looks identical to "after" to me.

**Comment by vinceliuice** [comment]
![g2](https://github.com/vinceliuice/Colloid-gtk-theme/assets/7604295/9ab5f298-51aa-4b56-90aa-8d29b34ee4ea)

**Comment by vinceliuice** [comment]
You can see the changes, not a lot, but still different

**Comment by vinceliuice** [comment]
I told you I rebuild libadwaita theme base on default libadwaita theme, so if you use the normal version then it's looks almost like default theme

**Comment by vinceliuice** [comment]
I'm still working on it to reproduce all previous theme elements

**Comment by vinceliuice** [comment]
Now you can run: `./install.sh -l fixed --tweaks normal rimless` to fix the color issue
