### ISSUE TITLE
[EVERFOREST] Incorrect background contrast in GTK3 applications

### ISSUE THREAD

**Issue by krstfz** [vinceliuice/Colloid-gtk-theme#166]
Hello,

I've noticed some contrast issues between theme variations. 
1) The Everforest theme option seems a little bit darker than the official pallete which leads to some inconsistent theming. I've also noticed that the background color is applied correctly _inside the theme settings_ however after the theme is applied, the background color is different.

![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/880f68f2-9dd4-4c3a-b7c0-6e7058be9df3)
-- Everforest - correct contrast in the Theme settings (#232a2e - bg_dim in everforest-medium palette)

![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/4423c881-c7e3-4b20-b0b8-ca42f1691f1a)
-- Everforest - inconsistent contrast (file manager on the left - #242932)

2) None of these issues persist with the other theme variants (such as Gruvbox - see below the GPick screenshot).

![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/5ae3a398-a259-4f3e-b336-b72c0e46c4e1)
-- Gruvbox - contrast matches up in Theme settings AND when it is applied aswell

![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/0966ea42-d7e0-46d9-a3f8-a1811a905405)
-- Gruvbox - all good

![obrazek](https://github.com/vinceliuice/Colloid-gtk-theme/assets/126676125/33837bad-4d79-4716-809a-b09d63c1d590)
-- GPick screenshot - here you can see the contrast inconsistency in the Everforest theme

I'm really not sure what could be the cause of this issue because the other theme options (Nord, Dracula & Gruvbox) work flawlessly and all theming is consistent throughout the whole system (with vim colorschemes, terminal themes etc.). I'm having trouble with the Everforest variant only.

Any help would be appreciated! Thank you

**Comment by vinceliuice** [comment]
Fixed now
