### ISSUE TITLE
add catppuccin color option

### ISSUE THREAD

**Issue by shadow-absorber** [vinceliuice/Colloid-gtk-theme#167]
after the catppuccin gtk theme got archived last week there is no more updates to fix bugs and stuff so this is a humble ask to add this as an option... you already got dracula and nord as themes so adding a single more colour option should not be to hard...

**Comment by shadow-absorber** [comment]
also #61 has started getting activity again because of this

**Comment by zt64** [comment]
Would it be possible to add the different variants? I personally don't like the one that's in colloid right now it's too light. Maybe using mocha for the dark theme and latte for the light theme

**Comment by vinceliuice** [comment]
You can try `./install.sh --tweaks catppuccin black`

**Comment by Aleksanaa** [comment]
> @zt64 You can try `./install.sh --tweaks catppuccin black`

Yeah that's mocha, thanks
