### ISSUE TITLE
Window buttons have changed

### ISSUE THREAD

**Issue by tio-trom** [vinceliuice/Colloid-gtk-theme#171]
I no longer see the colored window buttons but generic ones:

![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/38043315/de353ea8-04ac-4327-b47b-72100032c7a9)
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/38043315/a868bf50-3904-4c1d-a8a3-abc4bbdfdad8)

They used to be colored as showcased on your screenshots [here](https://github.com/vinceliuice/Colloid-gtk-theme?tab=readme-ov-file#colorschemes).

I see that the images for the buttons are now different:
![image](https://github.com/vinceliuice/Colloid-gtk-theme/assets/38043315/8747e7f0-3648-4f4d-b07e-d2ec1d1c9679)

Is this on purpose?

I am using TROMjaro (arch) + XFCE and the AUR package for this theme https://aur.archlinux.org/packages/colloid-gtk-theme-git

**Comment by jaygambrel** [comment]
Same issue for me on Manjaro Gnome after latest update.  Gnome 46 on Wayland. using the same AUR package as above.  Window buttons look like Adwaita despite following instructions:

To force Libadwaita applications to use the gtk-4.0 theme,
symlink the gtk-4.0 theme to config folder
mkdir -p ~/.config/gtk-4.0/
ln -sf /usr/share/themes/Colloid-Dark/gtk-4.0/{assets,gtk.css,gtk-dark.css} ~/.config/gtk-4.0/

Also set GTK_THEME in /etc/environment using the following line with no effect:
GTK_THEME=Colloid-Dark

**Comment by vinceliuice** [comment]
I checked AUR pkgbuild file
It add normal option in it so it will install normal windows buttons style.
You can install this theme from GitHub to get the colored one

**Comment by tio-trom** [comment]
Oh thank you I left a comment maybe the maintainer can fix it. This theme normally has the colored buttons so I wasn't even aware it had normal buttons too... Thanks for checking. I'll close this since it is AUR related.

**Comment by jaygambrel** [comment]
Thank you very much for sorting this out!  Downloading from GitHub sorted it for me as well.

**Comment by tio-trom** [comment]
> Thank you very much for sorting this out! Downloading from GitHub sorted it for me as well.

The AUR maintainer reverted the change. So it should be ok now. Wait for the repo to be updated if you are using a repo.
