### ISSUE TITLE
add support for XDG_BASE_DIRS

### ISSUE THREAD

**Issue by shadow-absorber** [vinceliuice/Colloid-gtk-theme#172]
add support for using the XDG base directories as specified here: [https://wiki.archlinux.org/title/XDG_Base_Directory](https://wiki.archlinux.org/title/XDG_Base_Directory)

or here: [https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

i.e themes should be placed in `XDG_DATA_HOME/themes` which defaults to `$HOME/.local/share/themes/`

**Comment by vinceliuice** [comment]
You can run `./install.sh -d $HOME/.local/share/themes/`

**Comment by shadow-absorber** [comment]
> You can run `./install.sh -d $HOME/.local/share/themes/`

yes but still supporting xdg_base_dirs by default is good... following the standards is good... they are there for a reason

**Comment by shadow-absorber** [comment]
not to mention a lot of people have this variable set by default or set it themselves in .zshenv or .profile and therefor the script would easily be able to use it by just looking... and as it already outputs the path it puts it in there will be no big confusion @vinceliuice

**Comment by vinceliuice** [comment]
I test it on my fedora, but it do not support `$XDG_DATA_HOME`

**Comment by shadow-absorber** [comment]
```
$XDG_DATA_HOME defines the base directory relative to which user-specific data files should be stored. If $XDG_DATA_HOME is either not set or empty, a default equal to $HOME/.local/share should be used. 
```
[https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html)

your patch seems to have broken the check too as `-n` is a check for if the string is not empty hence it will always return true from your added commit to install.sh... gonna submit another pull request that makes it work as you want it...
