### ISSUE TITLE
Kvantum version

### ISSUE THREAD

**Issue by nonetrix** [vinceliuice/Colloid-gtk-theme#174]
I like this theme and the fact it supports other color schemes, so a Kvantum version would be really neat in my opinion. Also, ideally would like if it would be packaged in Nix as well but that's just for my use cases, I have been moving away from GTK as much as possible considering recent direction of it

**Comment by vinceliuice** [comment]
it's here: https://github.com/vinceliuice/Colloid-kde

**Comment by nonetrix** [comment]
Same variants? I guess I should ask them though so I will close
