### ISSUE TITLE
Whisker menu does not look good on XFCE 4.18 (black border around whisker menu)

### ISSUE THREAD

**Issue by VentGrey** [vinceliuice/Colloid-gtk-theme#180]
The latest catppuccin palette draws a black border around the whisker menu in XFCE, all engines are installed. Tried building from source, same bug :)

![image](https://github.com/user-attachments/assets/07e076a8-ba28-44a3-b3d8-e12a06dd4a92)

**Comment by vinceliuice** [comment]
Open whisker menu setting, set the banckground opacity to 0
