### ISSUE TITLE
Gruvbox - window title not visible

### ISSUE THREAD

**Issue by tio-trom** [vinceliuice/Colloid-gtk-theme#190]
The active window title is not very visible. 

![image](https://github.com/user-attachments/assets/96144945-46e8-479d-aa1e-9ca3756c5aff)

**Comment by vinceliuice** [comment]
What's your desktop?

**Comment by tio-trom** [comment]
Sorry, XFCE

**Comment by tio-trom** [comment]
Seems to not happen with client-side decoration windows. But you can easily test it with any default xfce windows.

**Comment by vinceliuice** [comment]
OK, I'll check this
