### ISSUE TITLE
GNOME 47 issue

### ISSUE THREAD

**Issue by Drsheppard01** [vinceliuice/Colloid-gtk-theme#198]
Unvisible togglers in sound and brightness (GNOME 47, Chimera Linux)

![Снимок экрана от 2024-09-30 14-48-34](https://github.com/user-attachments/assets/f7b91cfd-0194-4d65-bbea-19074fb6c6a1)

Color scheme issue (border around button). 
![image](https://github.com/user-attachments/assets/2866dc86-a3f0-44af-b4d0-9c9dc55c4f67)

Chromium child window (like "Do u wanna restore your windows from previous session". Active button doesn't follow accent

Dialog in Nautilus

![image](https://github.com/user-attachments/assets/5d4067a4-3286-47dc-a4d5-175ae3d458f1)

**Comment by yudi7ll** [comment]
this two isn't fixed yet
![image](https://github.com/user-attachments/assets/ba0848dd-ac21-40c7-822b-27daae08932f)
![image](https://github.com/user-attachments/assets/44dab337-2b97-45b9-b52c-02fbb40fad4d)

**Comment by vinceliuice** [comment]
![Screenshot From 2024-11-16 22-07-14](https://github.com/user-attachments/assets/ca93d014-88d8-4bdd-ab01-6e85527f7aa1)

Download the last update and try again, it's already fixed
