### ISSUE TITLE
[Everforest, Gruvbox, Catppuccin] Nautilus without address bar and icons

### ISSUE THREAD

**Issue by luX0r-reload** [vinceliuice/Colloid-gtk-theme#201]
Hi.
This happen in Everforest with **color variant standard.**

- Ubuntu 24.04
- Nautilus 46.2

Theme installed with:

`./install.sh -t teal -c standard -s compact --libadwaita --tweaks everforest rimless float`

EDIT: same results with Gruvbox and Catppuccin palettes, but I think it is related to all palettes with the color variant standard.

![Screenshot from 2024-10-12 07-53-54](https://github.com/user-attachments/assets/60ea3499-6090-4f26-9919-499e5e6ea011)

**Comment by luX0r-reload** [comment]
It does not works.
In the following screeshots you can view nautilus in Adwaita and nautilus in Colloid (git cloned few minutes ago).

Installed with this:

`install.sh -t teal -c standard -s compact --libadwaita --tweaks everforest rimless float`

![nautilus-adwaita](https://github.com/user-attachments/assets/d9dd609a-84b1-40fb-bd8d-38fbf0ee11b3)
![nautilus-colloid](https://github.com/user-attachments/assets/6a72d808-efa6-4eae-b40e-3134e3c3e8d1)

**Comment by luX0r-reload** [comment]
It seems ok now, thanks!
A question: Is this space between the items intentionally? 

![nautilus-colloid-row-space](https://github.com/user-attachments/assets/31a97968-0d98-4148-bdb4-67f85d7e93ac)

**Comment by vinceliuice** [comment]
I'll fix the space issue

**Comment by vinceliuice** [comment]
now it's ok !

**Comment by luX0r-reload** [comment]
Yes, it's better now!

**Comment by luX0r-reload** [comment]
Hi.
Same problem with the tabs in Nautilus.

:-(

**Comment by luX0r-reload** [comment]
When in Nautilus there are more than one tab open, tabs are not showed... as address bar and icons in the previous bug (see above).

**Comment by luX0r-reload** [comment]
Hi.
Any news on this?

**Comment by vinceliuice** [comment]
Now it's fixed

**Comment by luX0r-reload** [comment]
For me it does not works :-(
When launch nautilus from terminal, it show me this warnings.

```
(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.978: Theme parser error: gtk.css:46:1-6: Unknown name of pseudo-class

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7954:15-19: Expected a valid color.

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7954:15-19: Junk at end of value for background

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7969:3-17: No property named "--accent-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7973:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7977:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7981:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7985:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7989:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7993:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:7997:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:8001:3-20: No property named "--accent-bg-color"

(org.gnome.Nautilus:5134): Gtk-WARNING **: 18:18:24.989: Theme parser error: gtk.css:8005:3-20: No property named "--accent-bg-color"

```

**Comment by vinceliuice** [comment]
Can not open nautilus ?

**Comment by luX0r-reload** [comment]
Many thanks, it works with the latest update!
