### ISSUE TITLE
The close ,minimize and max buttons are not styled on Cinnamon 4.6.7

### ISSUE THREAD

**Issue by madhur** [vinceliuice/Colloid-gtk-theme#22]
Running CentOS 8 with Cinnamon 4.6.7
These buttons are not styled as per the screenshots

**Comment by vinceliuice** [comment]
show me a screenshot

**Comment by madhur** [comment]
![Screenshot from 2022-02-04 11-28-40](https://user-images.githubusercontent.com/509431/152480085-5de5c017-b407-42f2-a316-48cab6f629e6.png)

**Comment by madhur** [comment]
In the screenshot above, the buttons are showing styled normal. I am using another theme to get Mac style buttons, but I want to get the same from Colloid.

**Comment by madhur** [comment]
![Themes_005](https://user-images.githubusercontent.com/509431/152480437-5dfd04ee-106a-47dc-811f-4ba1a596e63d.png)
This is with Colloid theme selected

**Comment by vinceliuice** [comment]
I'll update this

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Fixed !

**Comment by mseveritt** [comment]
Again, much appreciated!
