### ISSUE TITLE
Color variant

### ISSUE THREAD

**Issue by vanillamatcha** [vinceliuice/Colloid-gtk-theme#23]
hello vince, are there any plans to add color variations adopting from vscode theme, like dracula color.

**Comment by vinceliuice** [comment]
No problem!

**Comment by vinceliuice** [comment]
Added now, you can run `./install.sh --tweaks dracula` to install it

**Comment by vanillamatcha** [comment]
ahhh awesome, thank youu vince 😸

**Comment by vinceliuice** [comment]
You are welcome!
