### ISSUE TITLE
Cinnamon: WIFI-Button does not use nord colors

### ISSUE THREAD

**Issue by mseveritt** [vinceliuice/Colloid-gtk-theme#25]
In Cinnamon, the WIFI-Button (Network App in Panel) does not use nord colors (seen for teal). This affects Graphite GTK theme as well.
![image](https://user-images.githubusercontent.com/61334079/154248642-0f4bdaa2-de56-406e-aa98-fc8f2700ffa8.png)

**Comment by vinceliuice** [comment]
I'll fix this
