### ISSUE TITLE
GTK2: Hard readability, e.g. unselected checkboxes

### ISSUE THREAD

**Issue by mseveritt** [vinceliuice/Colloid-gtk-theme#30]
GTK2-apps are somewhat hard to read. 
E.g. unselected checkboxes are not shown and a differentiation of parts of the Apps are missing.
E.g. Asunder on Cinnamon 5.2.7 (teal nord rimless):
![grafik](https://user-images.githubusercontent.com/61334079/154737412-5988fd6d-de32-4a2a-b651-934f6e3a8a51.png)

In Graphite, this is way better (also teal nord rimless):
![grafik](https://user-images.githubusercontent.com/61334079/154737552-736ba902-f4b1-4bdb-a1f6-a4b930772b16.png)

**Comment by vinceliuice** [comment]
Fixed!
