### ISSUE TITLE
Cinnamon: narrow calender applet

### ISSUE THREAD

**Issue by mseveritt** [vinceliuice/Colloid-gtk-theme#31]
Dear Vince,
compared to Graphite, the cinnamon calender applet appears quite narrow (screenshots below). 
Is it possible to widen the appearance? 
Many thanks in advance.

(generated with install.sh: -c dark -t teal --tweaks nord rimless)  
![grafik](https://user-images.githubusercontent.com/61334079/154796426-a613c564-1fcf-4c3a-8cb7-fee9a010e129.png)

Graphite looks better:
![grafik](https://user-images.githubusercontent.com/61334079/154796487-99a1a9a6-ccb3-47dc-8cae-5a4061419d41.png)

**Comment by vinceliuice** [comment]
N0 problem!
