### ISSUE TITLE
How to edit the theme files?

### ISSUE THREAD

**Issue by nguyensang28** [vinceliuice/Colloid-gtk-theme#33]
This theme is kinda great for me, but i want to make a fork of it

However I don't know which SCSS files i need to edit, can you show me which files i need to edit? i also want to edit the window controls too

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Colloid-gtk-theme/tree/main/src/sass

**Comment by nguyensang28** [comment]
thanks
