### ISSUE TITLE
Metacity: Rim version without rim

### ISSUE THREAD

**Issue by mseveritt** [vinceliuice/Colloid-gtk-theme#38]
Dear Vince,
in the normal version (not rimless), there is a rim around GTK apps but not around the apps which are taken care of Metacity.
(./install.sh -c dark --tweaks nord, 
Cinnamon 5.2.7)
A GTK App on the left and metacity on the right:
![grafik](https://user-images.githubusercontent.com/61334079/155809705-f19c02b9-a57c-4e98-8113-e8540d3cb97b.png)

Is it possible to fix that?
Many thanks in advance for making this beautiful theme better and better.

**Comment by vinceliuice** [comment]
You can only have a highlight on top on metacity

**Comment by mseveritt** [comment]
As this is already the case, we can close the issue
