### ISSUE TITLE
window frame is black although I have selected the normal

### ISSUE THREAD

**Issue by Thub543** [vinceliuice/Colloid-gtk-theme#44]
![Bildschirmfoto vom 2022-03-31 10-41-44](https://user-images.githubusercontent.com/102725820/161014550-483df929-8f90-4f77-975c-9bda65c7a89a.png)
Yesterday I installed it and I noticed that the windows frames still dark. Everything else is as it should be.

**Comment by Thub543** [comment]
![grafik](https://user-images.githubusercontent.com/102725820/161017290-9ccc6801-8f20-4685-8d45-804cc28a3ae9.png)

**Comment by vinceliuice** [comment]
App (gtk) theme use the light one

**Comment by Thub543** [comment]
Sorry I dont understand, do you mean the bottom one? if yes it also doesnt work
![grafik](https://user-images.githubusercontent.com/102725820/161018705-1791df65-35b5-4fbf-91f4-447fbe67d16d.png)

**Comment by vinceliuice** [comment]
Maybe you need restart your desktop, this is my desktop:
![Screenshot from 2022-03-31 17-08-04](https://user-images.githubusercontent.com/7604295/161019975-44fc70b8-0881-4d25-ad7d-faf7ab58038d.png)

**Comment by Thub543** [comment]
ok weird stuff happend :D i just switched back to colloid and wanted to restart but suddenly the window frames changed to white... no idea why, nevertheless I appreaciate your help! Thank you
