### ISSUE TITLE
Window menu invisible in Firefox

### ISSUE THREAD

**Issue by Anifyuli** [vinceliuice/Colloid-gtk-theme#46]
Bro, I have a small bug in your latest release of this theme with politeness.

![Screenshot from 2022-04-09 16-31-15](https://user-images.githubusercontent.com/73734843/162578947-f5540100-6ee3-41fb-885a-c97e10bb3b8a.png)

Window menu (minimize, maximize, and close) only show after hover on that area, and this bug only tested on Firefox (on other apps can't reproduce this bug recently). Now I'm install older release of Colloid-gtk-theme.

I always wait your update with fulfill of proud and responsible. Thanks for create this theme and I love this theme. Bravo!!!

**Comment by vinceliuice** [comment]
What's you firefox version?

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by Anifyuli** [comment]
Ok, thanks, Bro. I use Firefox v 99
