### ISSUE TITLE
Cannot build on GNOME 3.38

### ISSUE THREAD

**Issue by VentGrey** [vinceliuice/Colloid-gtk-theme#51]
The packaged + built version on gnome-look works fine, however the slim version is not available so I tried comiling it by hand but there is a compile error:

```sh
sudo ./install.sh --theme default --color dark --size compact
gnome-shell 38
Installing '/usr/share/themes/Colloid-dark-compact'...
Error: File to import not found or unreadable: widgets-38-0.
        on line 32:1 of src/sass/gnome-shell/_common-temp.scss
        from line 7:1 of src/main/gnome-shell/gnome-shell-dark.scss
>> @import 'widgets-38-0';
```

Am I doing something wrong? I do have the needed engines + dependencies installed so idk what might be happening.

**Comment by vinceliuice** [comment]
Fixed now
