### ISSUE TITLE
All dark variants have the same purple color.

### ISSUE THREAD

**Issue by stpnwf** [vinceliuice/Colloid-gtk-theme#55]
All color variants are purple in the latest edit, despite the variant chosen. The only exception being the default. That one is blue, all others have the same purple accent color.

I downloaded the code from the Download as zip option in the project page rather than the latest Release because I am on gnome 38, and latest release doesn't work on it.

This is the command I used:
`./install.sh -t all -c dark`

![Screenshot from 2022-04-28 10-23-53](https://user-images.githubusercontent.com/81482539/165763743-aa424c16-2c79-4466-bffe-cfc0d467cb64.png)

Really like the theme. What software do you use to make/edit it? I would like to make some edits to it but I lack the CSS knowledge. 

Thanks in advance.

**Comment by mskf1383** [comment]
I have the same problem when use `--theme all` to create color variants. creating only one color variant OK.
