### ISSUE TITLE
How did you make the mockup with the MacBook?

### ISSUE THREAD

**Issue by Pocco81** [vinceliuice/Colloid-gtk-theme#6]
Hey! I've been trying to find this exact virtual screen [here](https://placeit.net/c/mockups/?search=macbook&page=11). But I couldn't find it. So maybe you made the mockup using something else?

Do you mind explaining me how to get this setup going? Thanks!

**Comment by vinceliuice** [comment]
[macbook-pro.zip](https://github.com/vinceliuice/Colloid-gtk-theme/files/7696447/macbook-pro.zip)

**Comment by vinceliuice** [comment]
I get this picture from apple homepage

**Comment by Pocco81** [comment]
Thanks! and btw, what do you use for designing in general? InkScape? Figma? Illustrator?

**Comment by vinceliuice** [comment]
Inkscape

**Comment by Pocco81** [comment]
thanks for the quick reply :)
