### ISSUE TITLE
Catpuccin version

### ISSUE THREAD

**Issue by pewduckwei** [vinceliuice/Colloid-gtk-theme#61]
Friend, will there be a version with catppuccin color?

**Comment by sadrach-cl** [comment]
https://github.com/catppuccin/gtk

**Comment by sadrach-cl** [comment]
> Friend, will there be a version with catppuccin color?

https://github.com/catppuccin/gtk

**Comment by ghostx31** [comment]
Hey @vinceliuice feel free to close this since we already have the repo at [catppuccin/gtk](https://github.com/catppuccin/gtk).

**Comment by cesorious** [comment]
Perhaps this should be reopened in light of [catppuccin/gtk being archived](https://github.com/catppuccin/gtk/issues/262)?

**Comment by nullishamy** [comment]
> Perhaps this should be reopened in light of [catppuccin/gtk being archived](https://github.com/catppuccin/gtk/issues/262)?

The archived repo has all the patches needed (aside from adding the variant to the build system) to add the Catppuccin palette to colloid. You could use this as a reference if you still want to implement it here. @cesorious

**Comment by shadow-absorber** [comment]
yeah would love for the catppuccin support to be continued somewhere but it sounds like gtk themes is a huge mess

**Comment by cesorious** [comment]
I could probably get catppuccin to work with colloid, but I fear I know too little of GTK to be able to rebase potential updates to the catppuccin theme

**Comment by shadow-absorber** [comment]
> I could probably get catppuccin to work with colloid, but I fear I know too little of GTK to be able to rebase potential updates to the catppuccin theme

well if you can keep it working in similar vain to dracula or nord with the options it should be mostly fine

**Comment by vinceliuice** [comment]
I'll add catppuccin colorschemes version

**Comment by vinceliuice** [comment]
Added now

**Comment by cesorious** [comment]
This is great, but it seems only two of the 4 catppuccin variants are present, and none of the catppuccin accents are present either.

**Comment by shadow-absorber** [comment]
> This is great, but it seems only two of the 4 catppuccin variants are present, and none of the catppuccin accents are present either.

if you use the --theme option from install.sh it seems you can select accent colors like red and blue and purple and stuff and it will pick from the catppuccin colors for those "accents" if that is what they are called

**Comment by cesorious** [comment]
Ahh, wasn't aware of that, nice, this unforutunately still leaves the issue of not having two of the dark catppuccin variants available. Perhaps something like cattppuccin-mocha, etc would be sensible?
