### ISSUE TITLE
[Bug] Theme for legacy applications does not change to the default or any other

### ISSUE THREAD

**Issue by hodunov** [vinceliuice/Colloid-gtk-theme#69]
Hi, thanks for the interesting theme, but I think I found a bug
I can't get rid of the style for **Legacy applications**.
As example: even if I change everything to default or any other - **settings** remain as on the screenshot.
```
OS: Fedora Linux 36 (Workstation Edition) x86_64
DE: GNOME 42.3.1 
```

![image](https://user-images.githubusercontent.com/59585233/183397764-16d838f8-cbdc-4d84-ae14-16033520e277.png)

**Comment by niluzz** [comment]
I have the same problem!

**Comment by vinceliuice** [comment]
Fixed! run `./install.sh -u libadwaita`

**Comment by niluzz** [comment]
> Fixed! run `./install.sh -u libadwaita`

Thank you I used this command and put the changes, everything worked! 
./install.sh -u libadwaita --tweaks

**Comment by hodunov** [comment]
But now there is the opposite problem - the default theme does not change to any other  :smile:

**Comment by kszinhu** [comment]
@hodunov 
> But now there is the opposite problem - the default theme does not change to any other smile

got any sollution ?

**Comment by kszinhu** [comment]
@hodunov 
> But now there is the opposite problem - the default theme does not change to any other

For me the error was due to an extension, take a look my issue  (#74)

**Comment by assssss330** [comment]
For me it still does not working.
I'm using fedora 38 workstation edition, and i guess it is because it the tweaks application the only option is "Legacy applications" button, instead of "Applications". Does anyone knows a work around??
