### ISSUE TITLE
KDE Plasma version

### ISSUE THREAD

**Issue by xqmate** [vinceliuice/Colloid-gtk-theme#7]
Hello Vince,

First off, I would like to thank you for your hard work. You have been creating a lot of awesome themes for the community, and this one surely is no exception! I really love the attention to the details and I particularly like the idea of giving the option of selecting variants (Nord is extremely elegant and beautiful!)

This might seem kind of early, but there's one question that comes to my head: are there any plans for a Plasma version of this theme?

**Comment by vinceliuice** [comment]
Yes this theme will support kde plasma, just need some more time , I'm making the graphite kde theme now, this one will be the next
