### ISSUE TITLE
GNOME 43 support (new quick settings and new Nautilus tabs broken)?

### ISSUE THREAD

**Issue by JurijOrlow** [vinceliuice/Colloid-gtk-theme#75]
Hello.
Is there any ETA on GNOME 43 support? Mainly fixing quick settings, Nautilus and just GIGANTIC top bars. Cheers!

**Comment by vinceliuice** [comment]
How to get gnome 43？fedora beta？

**Comment by JurijOrlow** [comment]
Yes, F37 Beta has GNOME 43, as far as I'm concerned by now it has full release, not GMOE 43 beta (and if not F37 beta, nightly build for sure has, I will check in a moment). Also "User themes" and "Dash to dock" extensions are working in GNIE 43/F37.

**Comment by vinceliuice** [comment]
OK, I'll download fedora 37 for testing

**Comment by vinceliuice** [comment]
Fixed now!

**Comment by JurijOrlow** [comment]
Awesome job, looks great. Only one thing I'm noticing now, new tabs in Nautilus look a bit odd - they are way too big and have a weird bit on the left, like a fraction of open tab before actual first tab. Screenshot shows it better. Left Fedora 37 with GNOME 43, right Fedora 36 with GNOME 42.
![Zrzut ekranu z 2022-10-02 15-42-08](https://user-images.githubusercontent.com/32055243/193457479-96de044b-0c9b-49f2-8198-a885bf178788.png)

**Comment by vinceliuice** [comment]
Try the last update

**Comment by JurijOrlow** [comment]
Absolutely perfect now! Is it just me, or Fedora should use Colloid as their default theme? Integrate it with settings like Ubuntu does with Yaru. It will be awesome...
