### ISSUE TITLE
how to use nord theme on gtk4/libadwaita

### ISSUE THREAD

**Issue by monkeboi9** [vinceliuice/Colloid-gtk-theme#78]
I love the theme but am i stuck on the dark theme for libadwaita/gtk4?

**Comment by vinceliuice** [comment]
For example: install nord dark theme for libadwaita `./install.sh -c dark --tweaks nord`

**Comment by bocsi** [comment]
i'm seeing the same issue.
Installing the theme with "./install.sh -c dark --tweaks nord rimless normal"
the links in the .config/gtk-4 folder never get created

**Comment by vinceliuice** [comment]
install.sh is updated, run: `./install.sh -c dark --tweaks nord rimless normal -l` now

**Comment by vinceliuice** [comment]
Now need add `-l` or `--libadwaita` to fix for libadwaita app
