### ISSUE TITLE
Dark on hover on titlebar buttons

### ISSUE THREAD

**Issue by stpnwf** [vinceliuice/Colloid-gtk-theme#79]
On hover on macOS, the close, minimize and fullscreen icon color is not white, but rather black with - I think - a small transparency to them. I believe WhiteSur does precisely this.

Could this be added as an installation option? I love this theme, but I am not a fan of the white over the titlebar buttons. I noticed the way the buttons are done in the this theme is different from WhiteSur, so I could not copy them over to Colloid. If you don't have plans to do it, could you give me some pointers about where I could make the edits to change that myself?

Thanks in advance.

**Comment by vinceliuice** [comment]
https://github.com/vinceliuice/Colloid-gtk-theme/blob/b8f6952ef11c2a8375cb48ec8089462885dbaa6b/src/sass/gtk/_common-3.0.scss#L3776

Change:
      color: if($colorscheme != 'dracula', white, rgba(black, 0.5));
to:
      color: rgba(black, 0.5);

**Comment by vinceliuice** [comment]
and gtk4:
https://github.com/vinceliuice/Colloid-gtk-theme/blob/b8f6952ef11c2a8375cb48ec8089462885dbaa6b/src/sass/gtk/_common-4.0.scss#L4524

Change:
`color: if($colorscheme != 'dracula', white, rgba(black, 0.5));`
to:
`color: rgba(black, 0.5);`

**Comment by vinceliuice** [comment]
then run `./install.sh`

**Comment by npv12** [comment]
> https://github.com/vinceliuice/Colloid-gtk-theme/blob/b8f6952ef11c2a8375cb48ec8089462885dbaa6b/src/sass/gtk/_common-3.0.scss#L3776
> 
> Change: `color: if($colorscheme != 'dracula', white, rgba(black, 0.5));` to: `color: rgba(black, 0.5);`



> and gtk4:
> 
> https://github.com/vinceliuice/Colloid-gtk-theme/blob/b8f6952ef11c2a8375cb48ec8089462885dbaa6b/src/sass/gtk/_common-4.0.scss#L4524
> 
> Change: `color: if($colorscheme != 'dracula', white, rgba(black, 0.5));` to: `color: rgba(black, 0.5);`

These changes works perfectly here. Thanks!
