### ISSUE TITLE
Fedora 36 system settings/software/etc. not applying theme. 

### ISSUE THREAD

**Issue by Surgikill** [vinceliuice/Colloid-gtk-theme#80]
Hi all. 

So I installed the colloid theme and it looks great. Only issue is, it does not apply the theme to the settings/software applications. The minimize/maximize/close buttons are applied, but the dark theme is not applied when I have that selected. I did what was suggested in #39 by copying the css files to the gtk4.0 directory, and that successfully applies the dark theme to the windows, but then it breaks the minimize/maximize/close buttons, they show up as default icons. Any idea on a resolution for this?

**Comment by vinceliuice** [comment]
Run ./install.sh -c dark to make libadwaita app use dark theme

**Comment by Surgikill** [comment]
Thank you

**Comment by vinceliuice** [comment]
You are welcome

**Comment by TCB13** [comment]
Debian 12 here, I installed the theme with `./install.sh -c light -l --tweaks rimless` and everything seems to have the theme except for the Files application. Any tips? Thank you.

**Comment by TCB13** [comment]
> Debian 12 here, I installed the theme with `./install.sh -c light -l --tweaks rimless` and it didn't apply, any tips?

Never mind, I was running as root.
