### ISSUE TITLE
natilus color problem on ubuntu 22.10 

### ISSUE THREAD

**Issue by furkanguzel161** [vinceliuice/Colloid-gtk-theme#84]
hello on ubuntu 22.10 color of the nautilus file browser is white can you fix it? 
![Screenshot from 2022-10-21 15-19-42](https://user-images.githubusercontent.com/81360830/197194187-74f761b5-4452-48c2-bc27-7947e67d808d.png)
![Screenshot from 2022-10-21 15-17-14](https://user-images.githubusercontent.com/81360830/197194190-aa6b6a48-ca85-4d77-8758-93fdeda1b1ce.png)

**Comment by vinceliuice** [comment]
Run: ./install.sh -c dark -l

**Comment by furkanguzel161** [comment]
i got an error with that command
![Screenshot from 2022-10-21 17-13-18](https://user-images.githubusercontent.com/81360830/197216759-37b1b285-bcee-41c8-a73b-7b7f8e66b4d6.png)


> Run: `./install.sh -c dark -l`

**Comment by furkanguzel161** [comment]
1.

**Comment by vinceliuice** [comment]
My fault, just run `./install.sh -c dark`

**Comment by furkanguzel161** [comment]
> My fault, just run `./install.sh -c dark`
 Thanks, it worked! But in order to see the changes reboot is necessary :)
