### ISSUE TITLE
Colloid Dark Dracula iconn not available on linux mint themes / how to get dark mode ./install.sh --tweaks black

### ISSUE THREAD

**Issue by andreangletti** [vinceliuice/Colloid-gtk-theme#85]
When I go on system settings and then themes, the icons from Colloid Dark Dracula are not showing up.
I have copied the folder into ./themes

It is not clear how to get the Dark mode through ./install.sh --tweaks black, could you please explain the procedure?

Thank you amazing theme!

**Comment by vinceliuice** [comment]
Black is not dark version, is a pure balck color version (more dark to the normal dark),
And you want the icon theme?
Just download here: https://github.com/vinceliuice/Colloid-icon-theme

**Comment by andreangletti** [comment]
thank you very much, it works now! amazing theme ;)
