### ISSUE TITLE
Black tweak doesn't work

### ISSUE THREAD

**Issue by othmanelhoufi** [vinceliuice/Colloid-gtk-theme#86]
Black tweak doesn't work, system settings and nautilus appearance stays Dark but not Black.

![image](https://user-images.githubusercontent.com/40344016/198282027-aa3bc978-414d-454c-ae8c-2ca80304425e.png)

![image](https://user-images.githubusercontent.com/40344016/198282348-89878936-baa0-416e-bd13-ac76cac67e26.png)

While other application appear Black ex. Tweaks.

![image](https://user-images.githubusercontent.com/40344016/198282404-7b57692f-f3e3-4881-b858-5e27c1568ee8.png)

System Info 
------------------- 
OS: Ubuntu 22.10 x86_64 
Host: XPS 15 9520 
Kernel: 5.19.0-23-generic 
Uptime: 25 mins 
Packages: 2830 (dpkg), 21 (snap) 
Shell: bash 5.2.2 
Resolution: 1920x1200 
DE: GNOME 43.0 
WM: Mutter 
WM Theme: Adwaita 
Theme: Colloid-Dark [GTK2/3] 
Icons: Reversal-orange-dark [GTK2/3] 
Terminal: qterminal 
Terminal Font: Ubuntu Mono 11 
CPU: 12th Gen Intel i7-12700H (20) @ 4.600GHz 
GPU: NVIDIA GeForce RTX 3050 Ti Mobile                                                                                
GPU: Intel Alder Lake-P                                                                                               
Memory: 4826MiB / 15670MiB

**Comment by vinceliuice** [comment]
Run `./install.sh --tweaks black -c dark`

**Comment by othmanelhoufi** [comment]
@vinceliuice works perfectly, thanks for your help and for this theme
