### ISSUE TITLE
Colloid breaks overview bluring in Ubuntu 22.04

### ISSUE THREAD

**Issue by YulBrinner90** [vinceliuice/Colloid-gtk-theme#91]
Hi, Vinceliuice. The Colloid theme seems to breack Blur-my-shell-extension in the overview bluring. The bluring of the panel and of the overview-folders works perfectly but not that of the overview that appears non-blured, solid, black. This doesn't happen with the default themes (ie. adwaita, yaru) and with your Whitesur but happens only with Colloid. The stranger thing is that this has happend with the new frash installation but not with the older one (6 months ago). The two installations (Ubuntu 22.04 with Gnome 42) are identical except for the encryption: the newer one is encrypted. I have installed Colloid typing "./install.sh -l --tweaks rimless". Can we do something to repair it?

Thanks you for your attention

**Comment by npv12** [comment]
I can also reproduce this. It seems to be happening after https://github.com/vinceliuice/Colloid-gtk-theme/commit/0b92d2d0b07063289027c1b4757bc94b36ee88d7 merge

**Comment by YulBrinner90** [comment]
Thanks a lot. Now it's perfect. Have a good day!
